### ISSUE TITLE
duckdb.ParserException:

### ISSUE THREAD

**Issue by cornpo** [yoheinakajima/babyagi#276]
What happened: Start babyagi.py. It starts llama.cpp. It returns the first task list. Crashes with duckdb parser error.

Versions: Python 3.10.9 Anaconda, chromadb-0.3.21 duckdb-0.7.1 (not running in docker)

The error:

```
Traceback (most recent call last):
  File "~/agi/babyagi/babyagi.py", line 509, in <module>
    main()
  File "~/agi/babyagi/babyagi.py", line 488, in main
    results_storage.add(task, result, result_id, vector)
  File "~/agi/babyagi/babyagi.py", line 203, in add
    len(self.collection.get(ids=[result_id], include=[])["ids"]) > 0
  File "~/anaconda3/envs/text/lib/python3.10/site-packages/chromadb/api/models/Collection.py", line 138, in get
    return self._client._get(
  File "~/anaconda3/envs/text/lib/python3.10/site-packages/chromadb/api/local.py", line 188, in _get
    db_result = self._db.get(
  File "~/anaconda3/envs/text/lib/python3.10/site-packages/chromadb/db/clickhouse.py", line 397, in get
    val = self._get(where=where_str, columns=columns)
  File "~/anaconda3/envs/text/lib/python3.10/site-packages/chromadb/db/duckdb.py", line 239, in _get
    val = self._conn.execute(
duckdb.ParserException: Parser Error: syntax error at or near "You"
LINE 1: ...e-prioritizing the following tasks: [\'You are a task creation AI that uses th...
```

The duckdb parser is expecting a command, but it's getting the line of text from the 'task result'?

**Comment by cornpo** [comment]
fixed by https://github.com/yoheinakajima/babyagi/pull/279
