### ISSUE TITLE
problem with local Wizard-Vicuna-13B-Uncensored

### ISSUE THREAD

**Issue by aseok** [yoheinakajima/babyagi#316]
Hi
facing following error for local Wizard-Vicuna-13B-Uncensored.ggml.q4_1:

error loading model: llama.cpp: tensor 'layers.27.attention_norm.weight' is missing from model
llama_init_from_file: failed to load model
Traceback (most recent call last):
  File "babyagi.py", line 118, in <module>
    llm = Llama(
  File ".../.local/lib/python3.8/site-packages/llama_cpp/llama.py", line 161, in __init__
    assert self.ctx is not None
AssertionError

**Comment by aseok** [comment]
seems a reboot solved it.
