### ISSUE TITLE
BabyAGI will not start

### ISSUE THREAD

**Issue by bimg21** [yoheinakajima/babyagi#343]
`~/babyagi$ pip install -r requirements.txt`

"Requirement already satisfied: scipy in /usr/lib/python3/dist-packages (from sentence-transformers>=2.2.2->chromadb==0.3.21->-r requirements.txt (line 3)) (1.8.0)
Collecting torchvision
  Using cached torchvision-0.15.2-cp310-cp310-manylinux1_x86_64.whl (6.0 MB)
Collecting torch>=1.6.0
Killed"

`~/babyagi$ python babyagi.py`

"Traceback (most recent call last):
  File "/home/kravinec/babyagi/babyagi.py", line 14, in <module>
    import chromadb
ModuleNotFoundError: No module named 'chromadb'"

`~/babyagi$ docker-compose up`

"...
  File "/home/kravinec/.local/lib/python3.10/site-packages/docker/api/client.py", line 221, in _retrieve_server_version
    raise DockerException(
docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', PermissionError(13, 'Permission denied'))"

Any way the script won't run. Is it problem on my side or what?

**Comment by bimg21** [comment]
For anyone having this problem; it is easily solved by `pip install chromadb`
