### ISSUE TITLE
Will not start with error

### ISSUE THREAD

**Issue by ruze00** [yoheinakajima/babyagi#350]
New virtual env, pip install -r requirements.txt, edited .env to add key.

Then, python babyagi.py results in:

```
Traceback (most recent call last):
  File "/Users/ruze/workspace/reg/babyagi/babyagi.py", line 14, in <module>
    import chromadb
  File "/Users/ruze/anaconda3/envs/agi/lib/python3.11/site-packages/chromadb/__init__.py", line 1, in <module>
    import chromadb.config
  File "/Users/ruze/anaconda3/envs/agi/lib/python3.11/site-packages/chromadb/config.py", line 1, in <module>
    from pydantic import BaseSettings
  File "/Users/ruze/anaconda3/envs/agi/lib/python3.11/site-packages/pydantic/__init__.py", line 206, in __getattr__
    return _getattr_migration(attr_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ruze/anaconda3/envs/agi/lib/python3.11/site-packages/pydantic/_migration.py", line 279, in wrapper
    raise PydanticImportError(
pydantic.errors.PydanticImportError: `BaseSettings` has been moved to the `pydantic-settings` package. See https://docs.pydantic.dev/2.0.2/migration/#basesettings-has-moved-to-pydantic-settings for more details.

For further information visit https://errors.pydantic.dev/2.0.2/u/import-error
```

**Comment by ruze00** [comment]
Solved:  it's a ChromaDB issue and pydantic needs to be downgraded to 1.9.0 until it's fixed in Chroma.
