### ISSUE TITLE
module 'chromadb' has no attribute 'PersistentClient' in docker

### ISSUE THREAD

**Issue by whatactuallyis** [yoheinakajima/babyagi#371]
While trying to `docker-compose up`, I get the following `AttributeError`. However, I don't receive such a thing in local running.

```
[+] Running 2/0
 ✔ Network babyagi_default  Created                                                                                                             0.0s
 ✔ Container babyagi        Created                                                                                                             0.0s
Attaching to babyagi
babyagi  | Using embedded DuckDB without persistence: data will be transient
babyagi  |
babyagi  | *****CONFIGURATION*****
babyagi  |
babyagi  | Name  : BabyAGI
babyagi  | Mode  : alone
babyagi  | LLM   : gpt-4
babyagi  |
babyagi  | *****USING GPT-4. POTENTIALLY EXPENSIVE. MONITOR YOUR COSTS*****
babyagi  |
babyagi  | *****OBJECTIVE*****
babyagi  |
babyagi  | Create a Flask app that could be deployed to the Vercel.com
babyagi  |
babyagi  | Initial task: Initialize a basic Flask application.
babyagi  |
babyagi  | Using results storage: Chroma (Default)
babyagi  | Traceback (most recent call last):
babyagi  |   File "/app/./babyagi.py", line 276, in <module>
babyagi  |     results_storage = try_weaviate() or try_pinecone() or use_chroma()
babyagi  |                                                           ^^^^^^^^^^^^
babyagi  |   File "/app/./babyagi.py", line 274, in use_chroma
babyagi  |     return DefaultResultsStorage()
babyagi  |            ^^^^^^^^^^^^^^^^^^^^^^^
babyagi  |   File "/app/./babyagi.py", line 195, in __init__
babyagi  |     chroma_client = chromadb.PersistentClient(
babyagi  |                     ^^^^^^^^^^^^^^^^^^^^^^^^^
babyagi  | AttributeError: module 'chromadb' has no attribute 'PersistentClient'
```

**Comment by whatactuallyis** [comment]
I resolved it by running `docker-compose up --build` which forces building the `Dockerfile`.
